// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdcbwkukjwfsxusfvddc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkY2J3a3Vrandmc3h1c2Z2ZGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzE3MDYsImV4cCI6MjA2OTE0NzcwNn0.zDrXQFBkxmHqG6qkcedQLJTFSjDsAgXgMhx-PqbnoTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});